version: "3"
services:
  server:
    container_name: list-server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5001"
    volumes:
      - .:/server
      - /server/node_modules

  client:
    container_name: list-client
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
